### ISSUE TITLE
Erro ao atualizar (Pacth) e deletar uma comra compartilhada

### ISSUE THREAD

**Issue by Dlucap** [Dlucap/WebApiEasyList#25]
Mensagem de erro: 
System.InvalidOperationException
  HResult=0x80131509
  Message=The instance of entity type 'CompraCompartilhada' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Update(TEntity entity)
   at EasyList.Data.Repository.Repository`1.<Atualizar>d__8.MoveNext() in C:\Users\ozzy-\source\repos\WebApiEasyList\src\EasyList.Data\Repository\Repository.cs:line 60
   
   Inconsistência ocorre pois antes de salvar a alteração é realizado uma busca no banco que está rastreada, quando é realizado o save no ef o mesmo se perde no contexto, normalmente é execuado o AsNoTracking(), mas no metodo buscar por id não e possível adicionar esse método.

**Comment by Dlucap** [comment]
Resolvido desabilitando o rastreamento a nível de instância de contexto / EF Core .
Desabilitando o rastreamento de consultas (No Tracking) - 
http://www.macoratti.net/18/04/efcore_notrack1.htm
