### ISSUE TITLE
erro ao deletar compra

### ISSUE THREAD

**Issue by Dlucap** [Dlucap/WebApiEasyList#42]
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> MySqlConnector.MySqlException (0x80004005): Cannot delete or update a parent row: a foreign key constraint fails (`easylist`.`itmcompra`, CONSTRAINT `FK_ItmCompra_COMPRAR_CompraId` FOREIGN KEY (`CompraId`) REFERENCES `comprar` (`Id`))
 ---> MySqlConnector.MySqlException (0x80004005): Cannot delete or update a parent row: a foreign key constraint fails (`easylist`.`itmcompra`, CONSTRAINT `FK_ItmCompra_COMPRAR_CompraId` FOREIGN KEY (`CompraId`) REFERENCES `comprar` (`Id`))
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 817
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 49
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 131
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior,

**Comment by Dlucap** [comment]
Verificar ordem em que está sendo deletado, bem provável que está tentando deletar a compra antes de deletar os itens da compra
